stages:
  - check
  - test

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  APT_CACHE_DIR: $CI_PROJECT_DIR/apt

before_script:
  - apt-get update -yq
  - apt-get install -o dir::cache::archives="$APT_CACHE_DIR" -y dbus

check:
  image: "registry.gitlab.com/alatiera/rustfmt-oci-image/rustfmt:stable"
  stage: "check"
  script:
    - rustc --version
    - cargo --version
    - cargo fmt --all -- --check

test:
  image: 'rust:latest'
  stage: test
  script:
    - rustc --version
    - cargo --version
    - mkdir -p /run/user/$UID
    - sed s/UID/$UID/ gitlab/dbus-session.conf > /tmp/dbus-session.conf
    - GET_MACHINE_ID=0 dbus-run-session --config-file /tmp/dbus-session.conf -- cargo test --verbose

cache:
  paths:
    - apt/
    - cargo/
    - target/
