[package]
name = "zvariant_derive"
# Keep version in sync with zvariant crate
version = "2.0.0"
authors = ["Zeeshan Ali <zeeshanak@gnome.org>"]
edition = "2018"

description = "API for D-Bus wire format encoding & decoding"
repository = "https://gitlab.freedesktop.org/zeenix/zbus/"
documentation = "http://docs.rs/zvariant/"
keywords = ["D-Bus", "DBus", "IPC"]
license = "MIT"
categories = ["data-structures", "encoding", "parsing"]
readme = "../README.md"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = "1.0.17"
quote = "1.0.3"

[dev-dependencies]
zvariant = { path = "../zvariant", features = [ "enumflags2" ] }
enumflags2 = { version = "0.6.4", features = [ "serde" ] }
serde = { version = "1.0", features = [ "derive" ] }
