[package]
name = "zbus"
version = "1.0.0"
authors = ["Zeeshan Ali <zeeshanak@gnome.org>"]
edition = "2018"

description = "API for D-Bus communication"
repository = "https://gitlab.freedesktop.org/zeenix/zbus/"
documentation = "http://docs.rs/zbus"
keywords = ["D-Bus", "DBus", "IPC"]
license = "MIT"
categories = ["os::unix-apis"]
readme = "../README.md"

[dependencies]
byteorder = "1.3.1"
nix = "0.13.0"
serde = "1.0"
serde_derive = "1.0"
#arrayvec = { version = "0.5.1", features = [ "serde" ] }
zvariant = { path = "../serde", version = "^2" }
