[package]
name = "zbus"
version = "1.0.0"
authors = ["Zeeshan Ali <zeeshanak@gnome.org>"]
edition = "2018"

description = "API for D-Bus communication"
repository = "https://gitlab.freedesktop.org/zeenix/zbus/"
documentation = "http://docs.rs/zbus"
keywords = ["D-Bus", "DBus", "IPC"]
license = "MIT"
categories = ["os::unix-apis"]
readme = "../README.md"

[dependencies]
byteorder = "1.3.1"
nix = "0.13.0"
serde = { version = "1.0", features = [ "derive" ] }
serde_repr = "0.1"
#arrayvec = { version = "0.5.1", features = [ "serde" ] }
zvariant = { path = "../zvariant" }
zvariant_derive = { path = "../zvariant_derive" }

[dev-dependencies]
enumflags2 = { version= " ^0.6", features = [ "serde" ] }
