[package]
name = "zbus-xmlgen"
version = "1.0.0"
authors = ["Marc-André Lureau <marcandre.lureau@redhat.com>"]
edition = "2018"

[dependencies]
zbus = { path = "../zbus", features = [ "xml" ] }
snakecase = "0.1.0"
