[package]
name = "zbus_xmlgen"
version = "1.0.0"
authors = [
    "Bilal Elmoussaoui <bil.elmoussaoui@gmail.com>",
    "Federico Mena Quintero <federico@gnome.org>",
    "Marc-André Lureau <marcandre.lureau@redhat.com>",
    "Thomas Mühlbacher <tmuehlbacher@posteo.net>",
    "Tim Small <tim@seoss.co.uk>",
    "Zeeshan Ali <zeeshanak@gnome.org>",
]
edition = "2018"

[[bin]]
name = "zbus-xmlgen"
path = "src/main.rs"

[dependencies]
zbus = { path = "../zbus", version = "1", features = ["xml"] }
zvariant = { path = "../zvariant", version = "2" }
snakecase = "0.1.0"
